# Generated by Django 3.1.1 on 2020-10-29 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='line',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='major',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='nim',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='phone_no',
            field=models.CharField(max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='uni',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('TRF', 'Transfer'), ('TWB', 'Twibbon'), ('KTM', 'Kartu Pelajar'), ('PRO', 'Proposal')], max_length=31)),
                ('info', models.TextField(default='')),
                ('proof', models.URLField(default='')),
                ('verified', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.participant')),
            ],
        ),
    ]
