# Generated by Django 3.1.1 on 2020-12-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_verified',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='verify_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
