# Generated by Django 3.0.7 on 2020-11-29 17:15

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validation',
            name='info',
        ),
        migrations.RemoveField(
            model_name='validation',
            name='proof',
        ),
        migrations.AddField(
            model_name='validation',
            name='file',
            field=models.FileField(default=None, upload_to=users.models.Validation.savedFileName),
        ),
    ]
