# Generated by Django 3.1.1 on 2020-12-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201129_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_verified',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='verify_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
