# Generated by Django 3.0.7 on 2020-11-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('payment', models.FileField(null=True, upload_to='')),
                ('twibbon', models.FileField(null=True, upload_to='')),
                ('twibbon_post', models.TextField(null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
