# Generated by Django 3.1.1 on 2020-10-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preevent',
            name='payment',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
