# Generated by Django 3.0.7 on 2020-11-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preevent',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='preevent',
            name='twibbon',
        ),
        migrations.RemoveField(
            model_name='preevent',
            name='twibbon_post',
        ),
        migrations.AddField(
            model_name='preevent',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='preevent',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
