# Generated by Django 3.1.1 on 2020-10-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_events', '0002_preevent_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='preevent',
            name='twibbon',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='preevent',
            name='twibbon_post',
            field=models.TextField(null=True),
        ),
    ]
