# Generated by Django 3.0.7 on 2020-12-03 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('OP', 'Operations'), ('MA', 'Marketing'), ('DN', 'Dunno')], max_length=31)),
                ('proposal', models.URLField(default='')),
                ('adv_to_finals', models.BooleanField(default=False)),
                ('Participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comp', to='users.Participant')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='competition.Team')),
            ],
        ),
    ]
